apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  labels:
    app: echoserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
  type: LoadBalancer
