apiVersion: scheduling.k8s.io/v1 #scheduling.k8s.io/v1beta1 for kubernetes version 1.13
kind: PriorityClass
metadata:
  name: low-priority
value: 10
globalDefault: false
description: "This priority class should be used for placeholder pods."
---
apiVersion: scheduling.k8s.io/v1 #scheduling.k8s.io/v1beta1 for kubernetes version 1.13
kind: PriorityClass
metadata:
  name: default-priority
value: 1000000
globalDefault: true
description: "This priority class should be used for standard pods."
